apiVersion: v2
name: deletion-blocker-operator
version: 0.6.2
appVersion: 0.6.2
description: "An helper operator to block deletion of k8s objects by managing finalizers based on some defined rules"
home: "https://github.com/giantswarm/deletion-blocker-operator"
icon: https://s.giantswarm.io/app-icons/giantswarm/1/dark.svg
annotations:
  io.giantswarm.application.team: "rocket"
  config.giantswarm.io/version: 1.x.x
